* Plate Tuning
:PROPERTIES:
:BLOG: bits4waves@bits4waves
:DATE: [2021-04-12 Mon 19:39]
:OPTIONS: toc:nil num:nil todo:nil pri:nil tags:nil ^:nil
:CATEGORY: Software
:POST_TAGS: software, plate tuning
:ID:       o2b:31dff5c3-5828-4fc5-aa88-7e991617862c
:POST_DATE: [2021-04-12 Mon 19:40]
:POSTID:   420
:END:

Greetings,

In a recent talk with a Luthier friend, he shared with me that plate tuning could get very tedious, because of the difficulties at each step to know exactly where to carve so as to obtain the desired impact on the final frequency.

Reading some papers, I came across a very interesting one, by Alan Carruth, a former student of Carleen Hutchins (attached carruth1991plate.pdf). In this article, the author gives a diagram with the impacts that carving might have on several different regions on the plate.

I then compiled this information in a spreadsheet, where you can input the desired final frequencies for the plates, and then feed it with the current ones. Based on this information, the spreadsheet will show diagrams with the regions that could be carved in order to achieve the final desired frequencies.

My friend liked it so much, that he encouraged me to share it to the Luthier community, so I'm sharing here with you.

Please feel free to post any questions, criticism, and any feedback is appreciated.

Thanks for your attention!

[[https://docs.google.com/spreadsheets/d/1flQmmzBa5rORl6uWclfxSgB1eQOwRGLfKLvUKZurYr0/copy][Prototype (Google Spreadsheet)]]
